name: cubseq-nf
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - docopt
  - black
  - pylint
  - git
  - tmux
  - lftp
  - wget
  # - icu
  - conda-forge::r-base
  - conda-forge::r-tidyverse
  - conda-forge::r-dplyr
  - conda-forge::r-docopt
  - conda-forge::r-cowplot
  - conda-forge::r-paletteer
  - conda-forge::r-ggrepel
  - conda-forge::r-vcfr
  - conda-forge::r-circlize
  - conda-forge::r-stringi # fixed tidyverse package version issue
  - conda-forge::gsl # needed to install bcftools correctly
  - conda-forge::matplotlib
  - conda-forge::tectonic
  - conda-forge::r-rlang>=1.1.3
  - conda-forge::r-dbi>=1.1.3
  # - conda-forge::r-scales>=1.3.0
  - bioconda::fastp
  - bioconda::star
  - bioconda::samtools
  - bioconda::bcftools
  - bioconda::subread
  - bioconda::freebayes
  - bioconda::salmon>=1.10.1
  - bioconda::gffread
  - bioconda::bedtools
  - bioconda::bioconductor-cordon
  - bioconda::bioconductor-tximport
  - bioconda::bioconductor-genomicfeatures>=
  - bioconda::bioconductor-KEGGREST
  - bioconda::bioconductor-Biostrings
  - bioconda::bioconductor-rtracklayer>=1.58.0
  - bioconda::bioconductor-complexheatmap
  - bioconda::seqkit