name: "build"
on: [push]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: containers/Dockerfile
          platforms: linux/amd64
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:1.3.1, ghcr.io/${{ github.repository }}:latest
      - name: 'Install Nextflow'
        uses: stracquadaniolab/gh-action-setup-nextflow@v0.2.0
      - name: 'Testing Nextflow pipeline with test profile'
        run: |
          chmod +x bin/*
          nextflow run . -profile test,ci -stub-run
      - name: Push image to GitHub container registry
        if: startsWith(github.event.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: containers/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:1.3.1, ghcr.io/${{ github.repository }}:latest